server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  Debug: true

logger:
    Development: true
    DisableCaller: false
    DisableStacktrace: false
    Encoding: json
    Level: info

postgres:
    PostgresqlHost: localhost
    PostgresqlPort: 5432
    PostgresqlUser: admin
    PostgresqlPassword: secret
    PostgresqlDbname: blog_db
    PostgresqlSslmode: false
    PgDriver: pgx