server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  Debug: true
  ReadTimeout: 5
  WriteTimeout: 5
  SymmetricKey: secret_token_symmetric_key_12345

logger:
    Development: true
    DisableCaller: false
    DisableStacktrace: false
    Encoding: console
    Level: info

postgres:
    PostgresqlHost: localhost
    PostgresqlPort: 5432
    PostgresqlUser: admin
    PostgresqlPassword: secret
    PostgresqlDbname: blog_db
    PostgresqlSslmode: false
    PgDriver: pgx

jaeger:
  Host: localhost:6831
  ServiceName: blogs_service
  LogSpans: false

redis:
  RedisHost: localhost:6379
  RedisPassword: ""
  RedisDb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240

minio:
  MinioEndpoint: 127.0.0.1:9000
  MinioAccessKey: DllHm00m9hJcqfxlWLWQ
  MinioSecretKey: M8WCdMfREGAs2x3hnIDKJg6v24L4Os2feTb0b9FR
  UseSSL: false

asynq:
  AsynqEndpoint: 127.0.0.1:6379
  AsynqPassword: ""
  AsynqDb: 0